## The profile with cache requires mysql, redis, zookeeper, kafka and maxwell.
## You can run `<jimmer_home>/example/env-with-cache/install.sh` to install them in docker

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_data
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
  kafka:
    consumer:
      bootstrap-servers: localhost:4003
      group-id: jimmer-demo/sql
      enable-auto-commit: false
      auto-offset-reset: latest
    listener:
      ack-mode: MANUAL_IMMEDIATE

jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect